### ISSUE TITLE
handshake

### ISSUE THREAD

**Issue by Guns29** [InventivetalentDev/WebFrames#2]
There appears to be an error with the plugin when trying to make a webframe it says fatal and about an handshake error 
 
AkA_The_One issued server command: /wfcreate https://www.youtube.com -w 4*128 -h 3*128
[11:39:47 WARN]: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
[11:39:47 WARN]:        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[11:39:47 WARN]:        at sun.security.ssl.Alerts.getSSLException(Unknown Source)
[11:39:47 WARN]:        at sun.security.ssl.SSLSocketImpl.recvAlert(Unknown Source)
[11:39:47 WARN]:        at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)
[11:39:47 WARN]:        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)
[11:39:47 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[11:39:47 WARN]:        at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
[11:39:47 WARN]:        at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)
[11:39:47 WARN]:        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
[11:39:47 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[11:39:47 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[11:39:47 WARN]:        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[11:39:47 WARN]:        at org.inventivetalent.webframes.WebFrames$API$1.run(WebFrames.java:144)
[11:39:47 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[11:39:47 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[11:39:47 WARN]:        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[11:39:47 WARN]:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[11:39:47 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by GunneR007** [comment]
a devs any fix yet for this issues

**Comment by Guns29** [comment]
well i guest this plugin is dead wow such a shame
